respurce_group_name    = "example-resources"
location               = "West Europe"
policy_name            = "only-deploy-in-westeurope"
policy_type            = "Custom"
policy_mode            = "All"
policy_display_name    = "policy-1"
policy_assignment_name = "example-policy-assignment"