module "loadbalancer" {
  source                                   = "../../modules/module_loadbalancer"
  lb_name                                  = var.lb_name
  resource_group_name                      = var.resource_group_name
  location                                 = var.location
  edge_zone                                = var.edge_zone
  lb_sku                                   = var.lb_sku
  lb_sku_tier                              = var.lb_sku_tier
  tags                                     = var.tags
  frontend_ip_configuration                = var.frontend_ip_configuration
  public_load_balancer_required            = var.public_load_balancer_required
  backend_address_pools_required           = var.backend_address_pools_required
  backend_address_pools                    = var.backend_address_pools
  backend_address_pools_addresses_required = var.backend_address_pools_addresses_required
  backend_address_pool_addresses           = var.backend_address_pool_addresses
  probe_required                           = var.probe_required
  probes                                   = var.probes
  load_balancing_rules_required            = var.load_balancing_rules_required
  load_balancing_rules_file_path           = var.load_balancing_rules_file_path
  outbound_rules_required                  = var.outbound_rules_required
  outbound_rules_file_path                 = var.outbound_rules_file_path
  nat_pools_required                       = var.nat_pools_required
  nat_pools                                = var.nat_pools
  nat_rules_required                       = var.nat_rules_required
  nat_rules_file_path                      = var.nat_rules_file_path
  use_nat_rules_frontend_port              = var.use_nat_rules_frontend_port
  use_nat_rules_frontend_range             = var.use_nat_rules_frontend_range
}
